root: true

exclude:
  - testdata/**
  - .git/**
  - .github/**
  - docs/**

rules:
  # Phase 0: Basic filesystem rules
  max-depth:
    max: 5

  max-files-in-dir:
    max: 20

  max-subdirs:
    max: 10

  # README.md Documentation Requirements
  # Every directory is like a building lobby - it needs a directory/guide
  # Format: "filename": "exists:count"
  file-existence:
    "README.md": "exists:1"

  disallowed-patterns:
    - "*.tmp"
    - "*.bak"
    - ".DS_Store"
    # Markdown Documentation Policy:
    # - README.md files: Required in every directory (see file-existence rule)
    # - Root-level exceptions: README.md, CONTRIBUTING.md, LICENSE.md
    # - All other .md files: Must be in docs/ folder
    # Disallow .md files in subdirectories, except README.md
    - "internal/**/*.md"
    - "cmd/**/*.md"
    - "examples/**/*.md"
    - "!**/README.md"  # Allow README.md files everywhere

# Phase 1: Architectural layers for Go project
layers:
  - name: cmd
    path: cmd/**
    dependsOn: [internal]

  - name: internal
    path: internal/**
    dependsOn: []

# Phase 2: Dead code detection
entrypoints:
  - cmd/structurelint/main.go
  - "**/*_test.go"

# Phase 3: Test File Validation (COMMENTED OUT - See docs/TEST_VALIDATION.md)
# Uncomment to enforce test file requirements
#
# test-adjacency:
#   pattern: "adjacent"              # Or "separate" for dedicated test directory
#   file-patterns:
#     - "**/*.go"
#   exemptions:
#     - "cmd/**/*.go"                # Exempt entry points
#     - "**/*_gen.go"                # Exempt generated files
#
# test-location:
#   integration-test-dir: "tests"    # Allow integration tests in tests/ folder
#   allow-adjacent: true             # Allow tests next to source code
#   exemptions:
#     - "testdata/**"

# Phase 4: File Content Templates (COMMENTED OUT - See docs/FILE_CONTENT_TEMPLATES.md)
# Uncomment to enforce file content structure
#
# file-content:
#   template-dir: ".structurelint/templates"
#   templates:
#     "**/README.md": "readme"         # Enforce README structure
#     "CONTRIBUTING.md": "contributing" # Enforce contributing guidelines
#     "docs/*.md": "design-doc"        # Enforce design doc structure
