root: true

exclude:
  - testdata/**
  - .git/**
  - .github/**
  - docs/**

rules:
  # Phase 0: Basic filesystem rules
  max-depth:
    max: 5

  max-files-in-dir:
    max: 25

  max-subdirs:
    max: 10

  # README.md Documentation Requirements
  # Every directory is like a building lobby - it needs a directory/guide
  # Format: "filename": "exists:count"
  file-existence:
    "README.md": "exists:1"

  disallowed-patterns:
    - "*.tmp"
    - "*.bak"
    - ".DS_Store"
    # Markdown Documentation Policy:
    # - README.md files: Required in every directory (see file-existence rule)
    # - Root-level exceptions: README.md, CONTRIBUTING.md, LICENSE.md
    # - All other .md files: Must be in docs/ folder
    # Disallow .md files in subdirectories, except README.md
    - "internal/**/*.md"
    - "cmd/**/*.md"
    - "examples/**/*.md"
    - "!**/README.md"  # Allow README.md files everywhere

  # Phase 3: Test File Validation
  # Files can use @structurelint:no-test directive to declare they don't need tests
  test-adjacency:
    pattern: "adjacent"              # Tests next to source code (Go convention)
    file-patterns:
      - "**/*.go"
    exemptions:
      - "cmd/**/*.go"                       # Entry points don't need tests
      - "**/*_gen.go"                       # Generated files
      - "**/*.py"                           # Exclude Python files (no source to test)
      - "internal/clones/**/*.go"           # POC clone detection (tests coming in Phase 3)

  test-location:
    integration-test-dir: "tests"    # Allow integration tests in tests/ folder
    allow-adjacent: true             # Allow tests next to source code
    file-patterns:                   # Explicitly scope to Go test files only
      - "**/*_test.go"
    exemptions:
      - "testdata/**"
      - "internal/rules/rules_test.go"  # Integration test for all rules
      - "tests/**/*.py"                  # Python test files in tests directory

  # Phase 4: File Content Templates
  file-content:
    template-dir: ".structurelint/templates"
    templates:
      "**/README.md": "readme"            # Enforce README structure
      "CONTRIBUTING.md": "contributing"    # Enforce contributing guidelines
      "**/*_test.go": "test-gwt-table"    # Enforce GWT naming + AAA for Go tests (supports table-driven)

  # API Specification Enforcement
  # Enforce OpenAPI for REST endpoints and AsyncAPI for event-driven systems
  # api-spec:
  #   require-openapi: true    # Require OpenAPI/Swagger spec when REST endpoints detected
  #   require-asyncapi: true   # Require AsyncAPI spec when event-driven patterns detected
  #   custom-specs: []         # Additional custom spec files to recognize

  # Design by Contract Framework Enforcement
  # Enforce established contract frameworks for better component contracts
  # contract-framework:
  #   require-python: true      # Python: icontract or deal
  #   require-rust: true        # Rust: Native assertions and type system
  #   require-typescript: true  # TypeScript: Zod for runtime validation
  #   require-go: true          # Go: gocontracts or standard assertions
  #   require-java: true        # Java: Jakarta Bean Validation 3.0 (JSR-380)
  #   require-csharp: true      # C#: Nullable reference types (Code Contracts deprecated)
  #   require-cplusplus: true   # C++: Native assertions (C++26 contracts in development)
  #   custom-frameworks: []     # Additional custom frameworks to recognize

  # Specification and ADR (Architecture Decision Record) Enforcement
  # Enforce documentation structure and templates for specs and ADRs
  # spec-adr-enforcement:
  #   require-spec-folder: true          # Require dedicated folder for specifications
  #   require-adr-folder: true           # Require dedicated folder for ADRs
  #   enforce-spec-template: true        # Validate specs follow feature specification template
  #   enforce-adr-template: true         # Validate ADRs follow ADR template
  #   spec-folder-paths:                 # Accepted locations for specs
  #     - "docs/specs"
  #     - "specifications"
  #   adr-folder-paths:                  # Accepted locations for ADRs
  #     - "docs/adr"
  #     - "docs/decisions"
  #   spec-file-patterns:                # Patterns for spec files
  #     - "*-spec.md"
  #     - "feature-*.md"
  #   adr-file-patterns:                 # Patterns for ADR files
  #     - "ADR-*.md"
  #     - "adr-*.md"
  #     - "*-decision.md"

# Phase 1: Architectural layers for Go project
layers:
  - name: cmd
    path: cmd/**
    dependsOn: [internal]

  - name: internal
    path: internal/**
    dependsOn: []

# Phase 2: Dead code detection
entrypoints:
  - cmd/structurelint/main.go
  - "**/*_test.go"
