root: true

exclude:
  - testdata/**
  - .git/**
  - .github/**
  - docs/**

rules:
  # Phase 0: Basic filesystem rules
  max-depth:
    max: 5

  max-files-in-dir:
    max: 30  # Increased for test files

  max-subdirs:
    max: 10

  # README.md Documentation Requirements
  # Every directory is like a building lobby - it needs a directory/guide
  # Format: "filename": "exists:count"
  file-existence:
    "README.md": "exists:1"

  disallowed-patterns:
    - "*.tmp"
    - "*.bak"
    - ".DS_Store"
    # Markdown Documentation Policy:
    # - README.md files: Required in every directory (see file-existence rule)
    # - Root-level exceptions: README.md, CONTRIBUTING.md, LICENSE.md
    # - All other .md files: Must be in docs/ folder
    # Disallow .md files in subdirectories, except README.md
    - "internal/**/*.md"
    - "cmd/**/*.md"
    - "examples/**/*.md"
    - "!**/README.md"  # Allow README.md files everywhere

  # Phase 3: Test File Validation
  # Files can use @structurelint:no-test directive to declare they don't need tests
  test-adjacency:
    pattern: "adjacent"              # Tests next to source code (Go convention)
    file-patterns:
      - "**/*.go"
    exemptions:
      - "cmd/**/*.go"                       # Entry points don't need tests
      - "**/*_gen.go"                       # Generated files

  test-location:
    integration-test-dir: "tests"    # Allow integration tests in tests/ folder
    allow-adjacent: true             # Allow tests next to source code
    exemptions:
      - "testdata/**"
      - "internal/rules/rules_test.go"         # Integration test for all rules
      - "internal/rules/test_adjacency.go"     # Not a test - rule implementation
      - "internal/rules/test_location.go"      # Not a test - rule implementation
      - "internal/rules/test_adjacency_test.go" # Has corresponding source
      - "internal/rules/test_location_test.go"  # Has corresponding source

  # Phase 4: File Content Templates
  file-content:
    template-dir: ".structurelint/templates"
    templates:
      "**/README.md": "readme"         # Enforce README structure
      "CONTRIBUTING.md": "contributing" # Enforce contributing guidelines

# Phase 1: Architectural layers for Go project
layers:
  - name: cmd
    path: cmd/**
    dependsOn: [internal]

  - name: internal
    path: internal/**
    dependsOn: []

# Phase 2: Dead code detection
entrypoints:
  - cmd/structurelint/main.go
  - "**/*_test.go"
