#!/bin/bash

# Script to check CI workflow status and artifacts
# For the artifact upload demonstration

echo "=========================================="
echo "CI Artifact Upload - Status Checker"
echo "=========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}Current Branch:${NC}"
git branch --show-current
echo ""

echo -e "${BLUE}Latest Commit:${NC}"
git log -1 --oneline
echo ""

echo -e "${BLUE}Remote Status:${NC}"
git status -sb
echo ""

echo "=========================================="
echo -e "${YELLOW}How to View the CI Run:${NC}"
echo "=========================================="
echo ""
echo "1. Open your browser and go to:"
echo -e "   ${GREEN}https://github.com/Jonathangadeaharder/structurelint/actions${NC}"
echo ""
echo "2. Look for the workflow run titled:"
echo "   'DEMO: Add failing test to trigger CI artifact upload'"
echo ""
echo "3. Click on that workflow run"
echo ""
echo "4. You should see:"
echo "   - Multiple jobs running (test, lint, complexity, build, self-lint)"
echo "   - Test job will FAIL (intentional)"
echo "   - Other jobs may pass or fail"
echo ""

echo "=========================================="
echo -e "${YELLOW}How to Download Artifacts:${NC}"
echo "=========================================="
echo ""
echo "Once the workflow completes (fails):"
echo ""
echo "1. On the workflow run page, scroll to the BOTTOM"
echo ""
echo "2. Look for the 'Artifacts' section"
echo ""
echo "3. You should see:"
echo "   - test-logs-Linux (if test job failed)"
echo "   - lint-logs-Linux (if lint job failed)"
echo "   - build-logs-ubuntu-latest (if build job failed)"
echo "   - etc."
echo ""
echo "4. Click any artifact name to download a ZIP file"
echo ""
echo "5. Extract the ZIP and view the log file:"
echo "   unzip test-logs-Linux.zip"
echo "   cat test.log"
echo ""

echo "=========================================="
echo -e "${YELLOW}Expected Artifact Contents:${NC}"
echo "=========================================="
echo ""
echo "The test.log file should contain:"
echo "  - Full test output from 'go test -v -race'"
echo "  - Our intentional failure message:"
echo "    '🎯 DEMO: This intentional test failure...'"
echo "  - All other test results"
echo "  - Stack traces (if any)"
echo "  - Race detector output (if any)"
echo ""

echo "=========================================="
echo -e "${YELLOW}Using GitHub CLI (if available):${NC}"
echo "=========================================="
echo ""
echo "# List recent workflow runs"
echo "gh run list --limit 5"
echo ""
echo "# Watch a specific run"
echo "gh run watch <run-id>"
echo ""
echo "# Download artifacts"
echo "gh run download <run-id>"
echo ""
echo "# Download specific artifact"
echo "gh run download <run-id> -n test-logs-Linux"
echo ""

echo "=========================================="
echo -e "${RED}⚠️  IMPORTANT: Cleanup After Testing${NC}"
echo "=========================================="
echo ""
echo "After you've verified the artifact upload works:"
echo ""
echo "1. Revert the demo changes:"
echo "   git revert HEAD"
echo "   git push"
echo ""
echo "2. Or manually remove:"
echo "   - The failing test in internal/metrics/artifact_test_demo.go"
echo "   - The branch trigger in .github/workflows/ci.yml"
echo ""
echo "3. This will make CI pass again and stop creating artifacts"
echo ""

echo "=========================================="
echo -e "${GREEN}✅ What Success Looks Like${NC}"
echo "=========================================="
echo ""
echo "Artifact Upload is working correctly when:"
echo ""
echo "✅ Workflow runs and test job fails"
echo "✅ 'Artifacts' section appears at bottom of run"
echo "✅ Can download 'test-logs-Linux.zip'"
echo "✅ ZIP contains 'test.log' file"
echo "✅ test.log has complete test output including our failure"
echo "✅ Artifact has 7-day retention period"
echo ""
echo "Once confirmed, revert the demo changes!"
echo ""

echo "=========================================="
echo -e "${BLUE}Quick Links${NC}"
echo "=========================================="
echo ""
echo "Actions page:"
echo "https://github.com/Jonathangadeaharder/structurelint/actions"
echo ""
echo "This branch:"
echo "https://github.com/Jonathangadeaharder/structurelint/tree/claude/software-quality-metrics-framework-01WfgH2HcdXAPN1gViMK79QV"
echo ""
echo "=========================================="
echo ""
echo "The CI workflow should be running now!"
echo "Check the Actions page in about 30-60 seconds."
echo ""
