sonar.projectKey=VidiomTM_structurelint
sonar.organization=vidiomtm
sonar.sources=.
sonar.language=go
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*_test.go,**/testdata/**,**/fuzz/**,**/examples/**,internal/parser/treesitter/**
sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPath=test.log
sonar.coverage.exclusions=clone_detection/**,tests/**
sonar.qualitygate.wait=true
