name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ["self-hosted", "macos", "arm64", "VidiomTM"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install goreleaser
        run: brew install goreleaser

      - name: Run goreleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
